"""create ImageValidationResult table

Revision ID: 9a8f864f06eb
Revises: 
Create Date: 2025-02-27 00:14:50.624985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8f864f06eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_validation_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_blank', sa.Boolean(), nullable=False),
    sa.Column('is_folded', sa.Boolean(), nullable=False),
    sa.Column('tilt_angle', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_validation_result')
    # ### end Alembic commands ###
