"""Init

Revision ID: a97548be1a6b
Revises: 
Create Date: 2025-03-15 20:52:45.314754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97548be1a6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_validation_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_blank', sa.Boolean(), nullable=False),
    sa.Column('is_folded', sa.Boolean(), nullable=False),
    sa.Column('tilt_angle', sa.Float(), nullable=False),
    sa.Column('gid', sa.Uuid(), nullable=False),
    sa.Column('message_received_time', sa.DateTime(), nullable=False),
    sa.Column('file_received_time', sa.DateTime(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_validation_result')
    # ### end Alembic commands ###
